namespace Alluseri.Luna;

public enum ClassAccessFlags : ushort {
	///	<summary>Declared public; may be accessed from outside its package.</summary>
	ACC_PUBLIC = 0x0001,
	/// <summary>Declared final; no subclasses allowed.</summary>
	ACC_FINAL = 0x0010,
	/// <summary>Treat superclass methods specially when invoked by the invokespecial instruction.</summary>
	ACC_SUPER = 0x0020,
	/// <summary>Is an interface, not a class.</summary>
	ACC_INTERFACE = 0x0200,
	/// <summary>Declared abstract; must not be instantiated.</summary>
	ACC_ABSTRACT = 0x0400,
	/// <summary>Declared synthetic; not present in the source code.</summary>
	ACC_SYNTHETIC = 0x1000,
	/// <summary>Declared as an annotation interface.</summary>
	ACC_ANNOTATION = 0x2000,
	/// <summary>Declared as an enum class.</summary>
	ACC_ENUM = 0x4000,
	/// <summary>Is a module, not a class or interface.</summary>
	ACC_MODULE = 0x8000
}
public enum FieldAccessFlags : ushort {
	///	<summary>Declared public; may be accessed from outside its package.</summary>
	ACC_PUBLIC = 0x0001,
	/// <summary>Declared private; accessible only within the defining class and other classes belonging to the same nest.</summary>
	ACC_PRIVATE = 0x0002,
	///	<summary>Declared protected; may be accessed within subclasses.</summary>
	ACC_PROTECTED = 0x0004,
	///	<summary>Declared static.</summary>
	ACC_STATIC = 0x0008,
	///	<summary>Declared final; never directly assigned to after object construction.</summary>
	ACC_FINAL = 0x0010,
	///	<summary>Declared volatile; cannot be cached.</summary>
	ACC_VOLATILE = 0x0040,
	///	<summary>Declared transient; not written or read by a persistent object manager.</summary>
	ACC_TRANSIENT = 0x0080,
	///	<summary>Declared synthetic; not present in the source code.</summary>
	ACC_SYNTHETIC = 0x1000,
	///	<summary>Declared as an element of an enum class.</summary>
	ACC_ENUM = 0x4000
}
public enum MethodAccessFlags : ushort {
	///	<summary>Declared public; may be accessed from outside its package.</summary>
	ACC_PUBLIC = 0x0001,
	///	<summary>Declared private; accessible only within the defining class and other classes belonging to the same nest(§5.4.4).</summary>
	ACC_PRIVATE = 0x0002,
	///	<summary>Declared protected; may be accessed within subclasses.</summary>
	ACC_PROTECTED = 0x0004,
	///	<summary>Declared static.</summary>
	ACC_STATIC = 0x0008,
	///	<summary>Declared final; must not be overridden(§5.4.5).</summary>
	ACC_FINAL = 0x0010,
	///	<summary>Declared synchronized; invocation is wrapped by a monitor use.</summary>
	ACC_SYNCHRONIZED = 0x0020,
	///	<summary>A bridge method, generated by the compiler.</summary>
	ACC_BRIDGE = 0x0040,
	///	<summary>Declared with variable number of arguments.</summary>
	ACC_VARARGS = 0x0080,
	///	<summary>Declared native; implemented in a language other than the Java programming language.</summary>
	ACC_NATIVE = 0x0100,
	///	<summary>Declared abstract; no implementation is provided.</summary>
	ACC_ABSTRACT = 0x0400,
	///	<summary>In a class file whose major version number is at least 46 and at most 60: Declared strictfp.</summary>
	ACC_STRICT = 0x0800,
	///	<summary>Declared synthetic; not present in the source code.</summary>
	ACC_SYNTHETIC = 0x1000
}