namespace Alluseri.Luna.Abstract.Bytecode;

public enum Opcode : byte {
	Nop,
	AConst_Null,
	IConst_M1, IConst_0, IConst_1, IConst_2, IConst_3, IConst_4, IConst_5,
	LConst_0, LConst_1,
	FConst_0, FConst_1, FConst_2,
	DConst_0, DConst_1,
	BiPush, SiPush,
	Ldc, Ldc_W, Ldc2_W,
	ILoad, LLoad, FLoad, DLoad, ALoad,
	ILoad_0, ILoad_1, ILoad_2, ILoad_3,
	LLoad_0, LLoad_1, LLoad_2, LLoad_3,
	FLoad_0, FLoad_1, FLoad_2, FLoad_3,
	DLoad_0, DLoad_1, DLoad_2, DLoad_3,
	ALoad_0, ALoad_1, ALoad_2, ALoad_3,
	IALoad, LALoad, FALoad, DALoad, AALoad, BALoad, CALoad, SALoad,
	IStore, LStore, FStore, DStore, AStore,
	IStore_0, IStore_1, IStore_2, IStore_3,
	LStore_0, LStore_1, LStore_2, LStore_3,
	FStore_0, FStore_1, FStore_2, FStore_3,
	DStore_0, DStore_1, DStore_2, DStore_3,
	AStore_0, AStore_1, AStore_2, AStore_3,
	IAStore, LAStore, FAStore, DAStore, AAStore, BAStore, CAStore, SAStore,
	Pop, Pop2, Dup, Dup_X1, Dup_X2, Dup2, Dup2_X1, Dup2_X2, Swap,
	IAdd, LAdd, FAdd, DAdd,
	ISub, LSub, FSub, DSub,
	IMul, LMul, FMul, DMul,
	IDiv, LDiv, FDiv, DDiv,
	IRem, LRem, FRem, DRem,
	INeg, LNeg, FNeg, DNeg,
	IShl, LShl, IShr, LShr, IUShr, LUShr,
	IAnd, LAnd, IOr, LOr, IXor, LXor,
	IInc,
	I2L, I2F, I2D,
	L2I, L2F, L2D,
	F2I, F2L, F2D,
	D2I, D2L, D2F,
	I2B, I2C, I2S,
	LCmp, FCmpL, FCmpG, DCmpL, DCmpG,
	If_0, If_Not0, If_LessThan0, If_GreaterEqual0, If_GreaterThan0, If_LessEqual0,
	If_ICmpEqual, If_ICmpNotEqual, If_ICmpLessThan, If_ICmpGreaterEqual, If_ICmpGreaterThan, If_ICmpLessEqual,
	If_ACmpEqual, If_ACmpNotEqual,
	Goto,
	JumpSubr, RetSubr,
	TableSwitch, LookupSwitch,
	IReturn, LReturn, FReturn, DReturn, AReturn, Return,
	GetStatic, PutStatic, GetField, PutField,
	InvokeVirtual, InvokeSpecial, InvokeStatic, InvokeInterface, InvokeDynamic,
	New, NewArray, ANewArray, ArrayLength,
	AThrow,
	CheckCast, InstanceOf,
	MonitorEnter, MonitorExit, Wide,
	MultiANewArray,
	IfNull, IfNotNull, Goto_W, JumpSr_W,
	Breakpoint, ImpDep1 = 254, ImpDep2
}